stages:
    - checkformat
    - monitor
    - compile
    - testcoverage

variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    COMPOSE_HTTP_TIMEOUT: "300"
    GIT_DEPTH: 1

checkformat:
    stage: checkformat
    image: docker/compose:latest
    tags:
        - builder
        - amd64
    script:
        - docker-compose -f ci.yml rm -f
        - docker-compose -f ci.yml up --build --exit-code-from=checkformat checkformat

# metric_loc_java:
#   stage: monitor
#   image: docker/compose:latest
#   tags:
#       - builder
#       - amd64
#   script:
#       - docker-compose -f ci.yml rm -f
#       - export CI_COMMIT_BRANCH
#       - docker-compose -f ci.yml up --build --exit-code-from=metric_loc_java metric_loc_java

# metric_loc_java_main:
#   stage: monitor
#   image: docker/compose:latest
#   tags:
#       - builder
#       - amd64
#   script:
#       - docker-compose -f ci.yml rm -f
#       - export CI_COMMIT_BRANCH
#       - docker-compose -f ci.yml up --build --exit-code-from=metric_loc_java_main metric_loc_java_main

# metric_loc_java_test:
#   stage: monitor
#   image: docker/compose:latest
#   tags:
#       - builder
#       - amd64
#   script:
#       - docker-compose -f ci.yml rm -f
#       - export CI_COMMIT_BRANCH
#       - docker-compose -f ci.yml up --build --exit-code-from=metric_loc_java_test metric_loc_java_test

compile:
    stage: compile
    image: docker/compose:latest
    tags:
        - builder
        - amd64
    script:
        - docker-compose -f ci.yml rm -f
        - docker-compose -f ci.yml up --build --exit-code-from=compile compile

# testcoverage:
#     stage: testcoverage
#     image: docker/compose:latest
#     tags:
#         - builder
#         - amd64
#     script:
#         - docker-compose -f ci.yml rm -f
#         - docker-compose -f ci.yml up --build --exit-code-from=testcoverage testcoverage
